- name: Tasks to download file
  hosts: localhost
  vars_files:
    - ./secret.yml

  tasks:
    - name: Create user dimzrio
      community.postgresql.postgresql_user:
        login_host: "{{ host }}"
        login_user: "{{ user }}"
        login_password: "{{ passwd }}"
        name: dimzrio
        password: "{{ dimzrio_passwd }}"
        expires: infinity

    - name: Create db dimzrio_db
      community.postgresql.postgresql_db:
        login_host: "{{ host }}"
        login_user: "{{ user }}"
        login_password: "{{ passwd }}"
        name: dimzrio_db

    - name: Create table dimzrio_tables on db dimzrio_db
      community.postgresql.postgresql_table:
        login_host: "{{ host }}"
        login_user: "{{ user }}"
        login_password: "{{ passwd }}"
        db: dimzrio_db
        name: dimzrio_tables